// AUTO-GENERATED by scripts/gen-db-types.mjs — do not edit by hand.
// Regenerate with: npm run db:types
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      characters: {
        Row: {
          class_id: string;
          created_at: string | null;
          id: string;
          level: number | null;
          name: string;
          user_id: string;
        };
        Insert: {
          class_id: string;
          created_at?: string | null;
          id?: string;
          level?: number | null;
          name: string;
          user_id: string;
        };
        Update: {
          class_id?: string;
          created_at?: string | null;
          id?: string;
          level?: number | null;
          name?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'characters_class_id_fkey';
            columns: ['class_id'];
            isOneToOne: false;
            referencedRelation: 'classes';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'characters_user_id_fkey';
            columns: ['user_id'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
        ];
      };
      classes: {
        Row: {
          created_at: string | null;
          id: string;
          image_url: string | null;
          name: string;
          parent_class: string | null;
        };
        Insert: {
          created_at?: string | null;
          id?: string;
          image_url?: string | null;
          name: string;
          parent_class?: string | null;
        };
        Update: {
          created_at?: string | null;
          id?: string;
          image_url?: string | null;
          name?: string;
          parent_class?: string | null;
        };
        Relationships: [];
      };
      donations: {
        Row: {
          amount: number;
          channel: string;
          created_at: string | null;
          currency: string;
          display_name: string;
          hide_amount: boolean;
          hide_from_wall: boolean;
          id: string;
          message: string | null;
          omise_charge_id: string | null;
          paid_at: string | null;
          provider: string;
          status: string;
          user_id: string | null;
        };
        Insert: {
          amount: number;
          channel: string;
          created_at?: string | null;
          currency?: string;
          display_name: string;
          hide_amount?: boolean;
          hide_from_wall?: boolean;
          id?: string;
          message?: string | null;
          omise_charge_id?: string | null;
          paid_at?: string | null;
          provider?: string;
          status?: string;
          user_id?: string | null;
        };
        Update: {
          amount?: number;
          channel?: string;
          created_at?: string | null;
          currency?: string;
          display_name?: string;
          hide_amount?: boolean;
          hide_from_wall?: boolean;
          id?: string;
          message?: string | null;
          omise_charge_id?: string | null;
          paid_at?: string | null;
          provider?: string;
          status?: string;
          user_id?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: 'donations_user_id_fkey';
            columns: ['user_id'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
        ];
      };
      dungeon_items: {
        Row: {
          default_price: number | null;
          dungeon_id: string;
          id: string;
          item_id: string;
        };
        Insert: {
          default_price?: number | null;
          dungeon_id: string;
          id?: string;
          item_id: string;
        };
        Update: {
          default_price?: number | null;
          dungeon_id?: string;
          id?: string;
          item_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'dungeon_items_dungeon_id_fkey';
            columns: ['dungeon_id'];
            isOneToOne: false;
            referencedRelation: 'dungeons';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'dungeon_items_item_id_fkey';
            columns: ['item_id'];
            isOneToOne: false;
            referencedRelation: 'items';
            referencedColumns: ['id'];
          },
        ];
      };
      dungeons: {
        Row: {
          id: string;
          image_url: string | null;
          name: string;
        };
        Insert: {
          id?: string;
          image_url?: string | null;
          name: string;
        };
        Update: {
          id?: string;
          image_url?: string | null;
          name?: string;
        };
        Relationships: [];
      };
      item_codes: {
        Row: {
          code: string;
          created_at: string;
          created_by: string | null;
          description: string | null;
          expire_date: string | null;
          id: string;
          start_date: string | null;
          updated_at: string;
        };
        Insert: {
          code: string;
          created_at?: string;
          created_by?: string | null;
          description?: string | null;
          expire_date?: string | null;
          id?: string;
          start_date?: string | null;
          updated_at?: string;
        };
        Update: {
          code?: string;
          created_at?: string;
          created_by?: string | null;
          description?: string | null;
          expire_date?: string | null;
          id?: string;
          start_date?: string | null;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'item_codes_created_by_fkey';
            columns: ['created_by'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
        ];
      };
      items: {
        Row: {
          default_price: number | null;
          game_item_id: number | null;
          icon: Json | null;
          id: string;
          name: string;
          rarity: string | null;
        };
        Insert: {
          default_price?: number | null;
          game_item_id?: number | null;
          icon?: Json | null;
          id?: string;
          name: string;
          rarity?: string | null;
        };
        Update: {
          default_price?: number | null;
          game_item_id?: number | null;
          icon?: Json | null;
          id?: string;
          name?: string;
          rarity?: string | null;
        };
        Relationships: [];
      };
      profiles: {
        Row: {
          avatar_url: string | null;
          created_at: string | null;
          id: string;
          role: string | null;
          username: string | null;
        };
        Insert: {
          avatar_url?: string | null;
          created_at?: string | null;
          id: string;
          role?: string | null;
          username?: string | null;
        };
        Update: {
          avatar_url?: string | null;
          created_at?: string | null;
          id?: string;
          role?: string | null;
          username?: string | null;
        };
        Relationships: [];
      };
      session_drops: {
        Row: {
          id: string;
          item_id: string;
          price_each: number | null;
          quantity: number | null;
          session_id: string;
        };
        Insert: {
          id?: string;
          item_id: string;
          price_each?: number | null;
          quantity?: number | null;
          session_id: string;
        };
        Update: {
          id?: string;
          item_id?: string;
          price_each?: number | null;
          quantity?: number | null;
          session_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'session_drops_item_id_fkey';
            columns: ['item_id'];
            isOneToOne: false;
            referencedRelation: 'items';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'session_drops_session_id_fkey';
            columns: ['session_id'];
            isOneToOne: false;
            referencedRelation: 'sessions';
            referencedColumns: ['id'];
          },
        ];
      };
      sessions: {
        Row: {
          character_id: string;
          created_at: string | null;
          dungeon_id: string | null;
          ended_at: string | null;
          gold_dropped: number | null;
          gold_earned: number | null;
          id: string;
          note: string | null;
          stamina_used: number | null;
          started_at: string | null;
          user_id: string;
        };
        Insert: {
          character_id: string;
          created_at?: string | null;
          dungeon_id?: string | null;
          ended_at?: string | null;
          gold_dropped?: number | null;
          gold_earned?: number | null;
          id?: string;
          note?: string | null;
          stamina_used?: number | null;
          started_at?: string | null;
          user_id: string;
        };
        Update: {
          character_id?: string;
          created_at?: string | null;
          dungeon_id?: string | null;
          ended_at?: string | null;
          gold_dropped?: number | null;
          gold_earned?: number | null;
          id?: string;
          note?: string | null;
          stamina_used?: number | null;
          started_at?: string | null;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'sessions_character_id_fkey';
            columns: ['character_id'];
            isOneToOne: false;
            referencedRelation: 'characters';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'sessions_dungeon_id_fkey';
            columns: ['dungeon_id'];
            isOneToOne: false;
            referencedRelation: 'dungeons';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'sessions_user_id_fkey';
            columns: ['user_id'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
        ];
      };
      site_counters: {
        Row: {
          count: number;
          key: string;
          updated_at: string;
        };
        Insert: {
          count?: number;
          key: string;
          updated_at?: string;
        };
        Update: {
          count?: number;
          key?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      skill_build_comments: {
        Row: {
          author_id: string;
          body: string;
          build_id: string;
          created_at: string | null;
          id: string;
        };
        Insert: {
          author_id: string;
          body: string;
          build_id: string;
          created_at?: string | null;
          id?: string;
        };
        Update: {
          author_id?: string;
          body?: string;
          build_id?: string;
          created_at?: string | null;
          id?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'skill_build_comments_author_id_fkey';
            columns: ['author_id'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'skill_build_comments_build_id_fkey';
            columns: ['build_id'];
            isOneToOne: false;
            referencedRelation: 'skill_builds';
            referencedColumns: ['id'];
          },
        ];
      };
      skill_build_likes: {
        Row: {
          build_id: string;
          created_at: string | null;
          user_id: string;
        };
        Insert: {
          build_id: string;
          created_at?: string | null;
          user_id: string;
        };
        Update: {
          build_id?: string;
          created_at?: string | null;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'skill_build_likes_build_id_fkey';
            columns: ['build_id'];
            isOneToOne: false;
            referencedRelation: 'skill_builds';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'skill_build_likes_user_id_fkey';
            columns: ['user_id'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
        ];
      };
      skill_builds: {
        Row: {
          allocations: Json;
          bonus_sp: number;
          char_level: number;
          class_id: number;
          comment_count: number;
          created_at: string | null;
          description: string | null;
          id: string;
          like_count: number;
          name: string;
          share_slug: string;
          updated_at: string | null;
          user_id: string;
          view_count: number;
          visibility: string;
        };
        Insert: {
          allocations: Json;
          bonus_sp?: number;
          char_level?: number;
          class_id: number;
          comment_count?: number;
          created_at?: string | null;
          description?: string | null;
          id?: string;
          like_count?: number;
          name?: string;
          share_slug: string;
          updated_at?: string | null;
          user_id: string;
          view_count?: number;
          visibility?: string;
        };
        Update: {
          allocations?: Json;
          bonus_sp?: number;
          char_level?: number;
          class_id?: number;
          comment_count?: number;
          created_at?: string | null;
          description?: string | null;
          id?: string;
          like_count?: number;
          name?: string;
          share_slug?: string;
          updated_at?: string | null;
          user_id?: string;
          view_count?: number;
          visibility?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'skill_builds_class_id_fkey';
            columns: ['class_id'];
            isOneToOne: false;
            referencedRelation: 'skill_classes';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'skill_builds_user_id_fkey';
            columns: ['user_id'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
        ];
      };
      skill_classes: {
        Row: {
          base_class: string;
          id: number;
          name: string;
          slug: string;
          sort_order: number;
        };
        Insert: {
          base_class: string;
          id: number;
          name: string;
          slug: string;
          sort_order?: number;
        };
        Update: {
          base_class?: string;
          id?: number;
          name?: string;
          slug?: string;
          sort_order?: number;
        };
        Relationships: [];
      };
      skills: {
        Row: {
          base_class: string | null;
          class_bits: number[];
          created_at: string | null;
          description: string | null;
          icon_url: string | null;
          id: number;
          levels: Json;
          max_level: number;
          name: string;
          parent_skill_id: number | null;
          positions: Json;
          prerequisites: Json;
          req_level: number;
          type: number;
          weapon_limit: number;
        };
        Insert: {
          base_class?: string | null;
          class_bits: number[];
          created_at?: string | null;
          description?: string | null;
          icon_url?: string | null;
          id: number;
          levels: Json;
          max_level?: number;
          name: string;
          parent_skill_id?: number | null;
          positions: Json;
          prerequisites: Json;
          req_level?: number;
          type?: number;
          weapon_limit?: number;
        };
        Update: {
          base_class?: string | null;
          class_bits?: number[];
          created_at?: string | null;
          description?: string | null;
          icon_url?: string | null;
          id?: number;
          levels?: Json;
          max_level?: number;
          name?: string;
          parent_skill_id?: number | null;
          positions?: Json;
          prerequisites?: Json;
          req_level?: number;
          type?: number;
          weapon_limit?: number;
        };
        Relationships: [
          {
            foreignKeyName: 'skills_parent_skill_id_fkey';
            columns: ['parent_skill_id'];
            isOneToOne: false;
            referencedRelation: 'skills';
            referencedColumns: ['id'];
          },
        ];
      };
      ticket_messages: {
        Row: {
          author_id: string;
          body: string;
          created_at: string | null;
          id: string;
          image_url: string | null;
          is_admin: boolean;
          ticket_id: string;
        };
        Insert: {
          author_id: string;
          body: string;
          created_at?: string | null;
          id?: string;
          image_url?: string | null;
          is_admin?: boolean;
          ticket_id: string;
        };
        Update: {
          author_id?: string;
          body?: string;
          created_at?: string | null;
          id?: string;
          image_url?: string | null;
          is_admin?: boolean;
          ticket_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'ticket_messages_author_id_fkey';
            columns: ['author_id'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'ticket_messages_ticket_id_fkey';
            columns: ['ticket_id'];
            isOneToOne: false;
            referencedRelation: 'tickets';
            referencedColumns: ['id'];
          },
        ];
      };
      tickets: {
        Row: {
          admin_last_read_at: string | null;
          created_at: string | null;
          id: string;
          last_sender_is_admin: boolean;
          status: string;
          subject: string;
          updated_at: string | null;
          user_id: string;
          user_last_read_at: string | null;
        };
        Insert: {
          admin_last_read_at?: string | null;
          created_at?: string | null;
          id?: string;
          last_sender_is_admin?: boolean;
          status?: string;
          subject: string;
          updated_at?: string | null;
          user_id: string;
          user_last_read_at?: string | null;
        };
        Update: {
          admin_last_read_at?: string | null;
          created_at?: string | null;
          id?: string;
          last_sender_is_admin?: boolean;
          status?: string;
          subject?: string;
          updated_at?: string | null;
          user_id?: string;
          user_last_read_at?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: 'tickets_user_id_fkey';
            columns: ['user_id'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
        ];
      };
    };
    Views: Record<string, never>;
    Functions: {
      admin_user_stats: {
        Args: Record<string, never>;
        Returns: {
          user_id: string;
          session_count: number;
          total_gold: number;
        }[];
      };
      increment_build_view: {
        Args: {
          build_slug: string;
        };
        Returns: Json;
      };
      increment_counter: {
        Args: {
          counter_key: string;
        };
        Returns: Json;
      };
    };
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};

export type Tables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Row'];
export type TablesInsert<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Insert'];
export type TablesUpdate<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Update'];
