-- AUTO-GENERATED dungeon-name seed.
-- Source: Dragonica client map string table
--   (Client/xml/defstrings/tb_defstrings_map.xml) — 250 dungeon names.
--
-- Curation applied to the raw string table:
--   * multi-floor dungeons collapsed to one row
--       ('Drakos Nth Fl.' -> 'Drakos'; 'Van Cliff Fortress ...' -> 'Van Cliff Fortress';
--        'Ice Palace - ...' -> 'Ice Palace'; '[Constellation Dungeon] Virgo ...' -> 'Virgo')
--   * dropped non-grind variants: Defense/Tactical/Bonus Stage, Corner, scenario,
--     War/PvP, and system maps (GM Room, MyHome, Chamber of Time, etc.)
--   * kept hard-mode grind targets (Dark / Elite / Chaos).
--
-- Idempotent: inserts only names not already present, so re-running adds nothing
-- and never duplicates. No schema change (no unique constraint required).

insert into dungeons (name)
select v.name
from (values
  ('Bearded Whale Coast'),
  ('Captain Hookah Villa'),
  ('Jigsaw Pincers Coast'),
  ('Decker Shark Piers'),
  ('Steven Trading Port'),
  ('Furious Captain Alvida'),
  ('Nautilus Port'),
  ('Kalygon Fleet'),
  ('Crazy Kalygon Captain'),
  ('Mirinae Sanctuary'),
  ('Evil Spirit Artis'),
  ('Skippy Sanctuary'),
  ('Evil Spirit, the Master'),
  ('Belkan Sanctuary'),
  ('Parmir Sanctuary'),
  ('Windia Plains'),
  ('Breathless Vagabond'),
  ('Advanced Windia Plains'),
  ('Wild Vegas'),
  ('Traitor''s Ridge'),
  ('Giant Axe Brother Sanka'),
  ('Howling Winds Hill'),
  ('Wailing Hill'),
  ('Canyon of Oblivion'),
  ('Giant Axe Brother Kunka'),
  ('Howling Wind''s Hill Wolves'' Den'),
  ('Wailing Hill Wolves'' Den'),
  ('City Hall Sewer'),
  ('Dr. Farrell''s Laboratory'),
  ('Dangerous Caverns'),
  ('Mambo Raccoon Ahtoo'),
  ('Culvert'),
  ('Mining Area'),
  ('Temple of Water'),
  ('Spirit of Water Endairon'),
  ('Citadel of Torment'),
  ('Hero''s Altar'),
  ('Lv.30 Underground Graveyard'),
  ('Lv.35 Underground Graveyard'),
  ('Wrath of Nautilus'),
  ('Dangerous Shrines'),
  ('Crisis of Windia Plains'),
  ('Barlok''s Lair'),
  ('Disordered Port'),
  ('Ocean Grave'),
  ('Silent Sanctuary'),
  ('Forgotten Temple'),
  ('Streets of Beast'),
  ('Wind Hills'),
  ('Rumored Forest'),
  ('Forest of Greed'),
  ('Wailing Ridge'),
  ('Thieves'' Den'),
  ('Master Chocolatier''s House'),
  ('Coral Fields'),
  ('Chocolate Storehouse'),
  ('Cookie Factory Mission'),
  ('Mallow Woodi'),
  ('Cookie Factory Biscuit Street'),
  ('Wedding Hall'),
  ('Cherry Blossom Hill'),
  ('Cherry Blossom Event Mission'),
  ('Steel Chef'),
  ('Red Queen Castle Entrance'),
  ('Red Queen Castle'),
  ('Red Queen'),
  ('Geffen Town'),
  ('Orc Field'),
  ('Glast Heim'),
  ('Port of the Winds'),
  ('Odelia'),
  ('1 Star Emporia'),
  ('2 Star Emporia'),
  ('3 Star Emporia'),
  ('4 Star Emporia'),
  ('5 Star Emporia'),
  ('Moonlight Shore Village'),
  ('Libra'),
  ('Wrecked Ship'),
  ('Valid Raeth'),
  ('Chief Rocker'),
  ('Abyss of Fire'),
  ('Magma Coral Fields'),
  ('Magma Drake Lavalon'),
  ('Magma Dungeon'),
  ('Drake Lavalon'),
  ('Scalding Swamps'),
  ('Queen Vella'),
  ('Dried Woods Swamp'),
  ('Reed Swamp'),
  ('Misty Lane'),
  ('Pine Cone Hills'),
  ('Pine Cone Lumbermill Field'),
  ('Wasted Lumbermill Field'),
  ('Woodsman Burnaun'),
  ('Gods'' Sanctuary'),
  ('Karkarous'),
  ('Collapsed Sanctuary'),
  ('Kayron Altar'),
  ('Ancient Golem Aram'),
  ('Kundara Dungeon'),
  ('Altar of Verdure'),
  ('Verdurous Forest'),
  ('Muddy Swamp'),
  ('Oak Lumbermill Field'),
  ('Cursed Shrine'),
  ('Lava Factory'),
  ('Crimson Field'),
  ('Smoldering Swamp'),
  ('Azure Altar'),
  ('Stone Statue Road'),
  ('Fungoid Village'),
  ('Forgotten Village'),
  ('Mimir King Bubobubo'),
  ('Tutu Tree Forest'),
  ('Village of Slumber'),
  ('Flickering Burlune'),
  ('Ruined Mushroom Factory'),
  ('Land of Temptation'),
  ('Golem Pythanuth'),
  ('Blizzard Ridge'),
  ('Frost Lake'),
  ('Frigid Canyon'),
  ('Ice Princess Arka'),
  ('Storm Snowfield'),
  ('Altar of Truth'),
  ('Drakos'),
  ('Bottomless Dark Altar'),
  ('Van Cliff Fortress'),
  ('Frozen Altar'),
  ('Ice Temple'),
  ('Rancorous Forest'),
  ('Chaser''s Ridge'),
  ('Chaser''s Ridge Arcade Elite'),
  ('Haven of Peace'),
  ('Haven of Peace Arcade Elite'),
  ('Snowy Graveyard'),
  ('Marshmallow Valley'),
  ('Verglas Ridge'),
  ('Verglas Ridge Arcade Elite'),
  ('Bear Claw Mine'),
  ('Bear Claw Mine Arcade Elite'),
  ('Ice Rock Hill'),
  ('Forest of Illusion'),
  ('Crystal Lake of Spirit'),
  ('Mushroom Tree Felling Area'),
  ('Firefly Mushroom Forest'),
  ('Poison Shroom Lake'),
  ('Poison Fog Road'),
  ('Fugitive''s Forest'),
  ('Frozen Mushroom Forest'),
  ('Moonlight Lake'),
  ('Frozen Field'),
  ('Ellora Camp'),
  ('Village of Ash Mist'),
  ('Frozen Bridge'),
  ('Frozen Grave'),
  ('Verglas Forest'),
  ('Bear Claw Ridge'),
  ('Bear Claw Hill'),
  ('Alexandre'),
  ('Salvalon'),
  ('Guardian Captain Jaro'),
  ('Lamieta'),
  ('Lamieta Kelo'),
  ('Eruda Valley'),
  ('Dragon Valley'),
  ('Dragon Valley Arcade Elite'),
  ('Nail Hill'),
  ('Wing Gorge'),
  ('Edge of the World'),
  ('Edge of the World Arcade Elite'),
  ('Depraved Altar'),
  ('Akia Cave'),
  ('Dark Altar'),
  ('Black Claw Nest'),
  ('Dimensional Room Entrance'),
  ('Mirage Hill'),
  ('Sandstorm Desert'),
  ('Sandstorm Desert Arcade Elite'),
  ('Wasteland'),
  ('Wasteland Arcade Elite'),
  ('Hydron Core'),
  ('Red Fox Delta'),
  ('Vartika Hill'),
  ('Coco Tooth'),
  ('Vanshi Gorge'),
  ('Dragon Valley Chaos Elite'),
  ('Edge of the World Chaos Elite'),
  ('Sandstorm Desert Chaos Elite'),
  ('Wasteland Chaos Elite'),
  ('Kazeura Village'),
  ('Dragon Valley Demon Prokell'),
  ('Edge of the World Kashape'),
  ('Ice Guardians'' Dungeon'),
  ('Fire Guardians'' Dungeon'),
  ('Dark Guardians'' Dungeon'),
  ('Nature Guardians'' Dungeon'),
  ('Black Claw Nest Outpost'),
  ('Warrior Tutorial'),
  ('Hooroo Plain'),
  ('Hooroo Botanic Garden'),
  ('Ice Palace'),
  ('Dark Bearded Whale Coast'),
  ('Dark Captain Hookah Villa'),
  ('Dark Steven Trading Port'),
  ('Dark Furious Captain Alvida'),
  ('Dark Kalygon Fleet'),
  ('Dark Mad Kalygon Captain'),
  ('Dark Mirinae Sanctuary'),
  ('Death Master Spirit'),
  ('Dark Skippy Sanctuary'),
  ('Evil Spirit, the Dead Master'),
  ('Dark Dangerous Caverns'),
  ('Dark Mambo Raccoon Ahtoo'),
  ('Dark Valid Raeth'),
  ('Dark Chief Rocker'),
  ('Dark Scalding Swamps'),
  ('Dark Queen Vella'),
  ('Dark Pine Cone Hills'),
  ('Dark Woodsman Burnaun'),
  ('Deserted Gods'' Sanctuary'),
  ('Chaser''s Ridge Chaos Elite'),
  ('Dark Chaser''s Ridge'),
  ('Dark Haven of Peace'),
  ('Dark Verglas Ridge'),
  ('Verglas Ridge Chaos Elite'),
  ('Dark Bear Claw Mine'),
  ('Dark Forgotten Village'),
  ('Dark Village of Slumber'),
  ('Dark Land of Temptation'),
  ('Golem Pythanus'),
  ('Dark Vartika Hill'),
  ('Dark Lamieta'),
  ('Dark Salvalon'),
  ('Dark Dragon Valley'),
  ('Dark Edge of the World'),
  ('Haven of Peace Chaos Elite'),
  ('Bear Claw Mine Chaos Elite'),
  ('Aries'),
  ('Taurus'),
  ('Gemini'),
  ('Cancer'),
  ('Leo'),
  ('Virgo'),
  ('Pegasus'),
  ('Scorpio'),
  ('Sagittarius'),
  ('Hydra'),
  ('Ophiuchus')
) as v(name)
where not exists (
  select 1 from dungeons d where d.name = v.name
);
